### ISSUE TITLE
Trying to renew Home address simply redirects to the Google Play Store

### ISSUE THREAD

**Issue by TheLastProject** [privacybydesign/irmamobile#10]
I suppose this is more of an issue with services.nijmegen.nl, but I wasn't sure where to better report it.

Open app -> Refresh card -> Inloggen met DigiD -> Redirect to Google Play Store

I've created a video to show the problem: https://streamable.com/hogqt6

IRMA: org.irmacard.cardemu 6.0.9
Browser: org.mozilla.firefox 82.1.1
DigiD: nl.rijksoverheid.digid.pub 5.16.1

**Comment by sietseringers** [comment]
This is because by default, Firefox refuses to listen to `intent://` or to Universal Links. The problem goes away if you enable the "Open links in apps" toggle in the Firefox settings.

**Comment by TheLastProject** [comment]
Well, that is a working workaround at least.

I assume the fact that this issue is left open means you do agree that making it work by default (like, a landing page or so with a clickable "Add to IRMA" and "Install IRMA") would be preferable?

**Comment by sietseringers** [comment]
No, I left the issue open here because usually I leave that to the issue author if and when they're satisfied 🙂  We are however working on a workaround that should sort of solve it, but that will not be in this project (but in [this one](https://github.com/privacybydesign/universal-link-fallback/pull/1)).

**Comment by TheLastProject** [comment]
Well, https://github.com/privacybydesign/universal-link-fallback/pull/1 is definitely both the better repository and will fix this issue so I'll close this in favour of that :)
