### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by GTP95** [privacybydesign/irmamobile#101]
Greetings,

I'm creating a Docker image with all the dependencies needed to build the IRMA app. I installed all the dependencies and (recursively) cloned the current version of this repo, but if I try to build the app with the command `flutter build apk` inside the repo's root, I get the following error: `e: /root/flutter/.pub-cache/git/flutter_privacy_screen-a3c29f667d5a556cf0280f1b39851a2707f788be/android/src/main/kotlin/be/appmire/flutter_privacy_screen/FlutterPrivacyScreenPlugin.kt: (21, 63): Smart cast to 'Activity' is impossible, because 'registrar.activity()' is a complex expression`
You can find the full output [here](https://pastebin.com/dPVtv7Wk). Are you able to build the current version? Maybe I have to checkout a particular branch?
Thank you for your help,

GTP

**Comment by ivard** [comment]
This is probably a Java / Gradle / Kotlin version mismatch. We'll merge our `ux-2.0` branch to master tomorrow. Maybe you can test again then to check whether the version changes we made there help you.

**Comment by GTP95** [comment]
I pulled the latest version of the code, after your merge. Build still fails, but with a different error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkAlphaReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:alphaReleaseRuntimeClasspath'.
   > Failed to transform irmagobridge.aar (project :irmagobridge) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /root/irmamobile/android/irmagobridge/irmagobridge.aar.
         > Transform's input file does not exist: /root/irmamobile/android/irmagobridge/irmagobridge.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 44s
Running Gradle task 'assembleRelease'...                          405.3s

┌─ Flutter Fix ─────────────────────────────────────────────────────────────────────────────────┐
│ This issue appears to be https://github.com/flutter/flutter/issues/58247.                     │
│ Fix this issue by adding the following to the file /root/irmamobile/android/app/build.gradle: │
│ android {                                                                                     │
│   lintOptions {                                                                               │
│     checkReleaseBuilds false                                                                  │
│   }                                                                                           │
│ }                                                                                             │
└───────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
```
Adding the suggested option to the lintOptions didn't fix it. Any idea on how to fix this?

**Comment by GTP95** [comment]
Turns out that I forgot to install go inside the container, but if I try to install gomobile as you describe in the README, I get the following error:
```
# go install golang.org/x/mobile/cmd/gomobile@latest
can't load package: package golang.org/x/mobile/cmd/gomobile@latest: cannot find package "golang.org/x/mobile/cmd/gomobile@latest" in any of:
	/usr/lib/go-1.10/src/golang.org/x/mobile/cmd/gomobile@latest (from $GOROOT)
	/root/go/src/golang.org/x/mobile/cmd/gomobile@latest (from $GOPATH)
```

**Comment by GTP95** [comment]
That was indeed a Go issue, now works. Thank you for helping
