### ISSUE TITLE
IOS builds fail when using Golang 1.20: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by sjoerdlmkns** [privacybydesign/irmamobile#117]
In the build-app-ios action the following error occurres: 

` Undefined symbols for architecture arm64:
      "_res_9_nclose", referenced from:
          _internal/syscall/unix.libresolv_res_9_nclose_trampoline.abi0 in Irmagobridge(go.o)
      "_res_9_ninit", referenced from:
          _internal/syscall/unix.libresolv_res_9_ninit_trampoline.abi0 in Irmagobridge(go.o)
      "_res_9_nsearch", referenced from:
          _internal/syscall/unix.libresolv_res_9_nsearch_trampoline.abi0 in Irmagobridge(go.o)
    ld: symbol(s) not found for architecture arm64`

**Comment by sjoerdlmkns** [comment]
https://github.com/golang/go/issues/58416

**Comment by ivard** [comment]
Closed by accident. The mentioned fix was a work around.

**Comment by drew-512** [comment]
Thanks for working this -- running into this too.

**Comment by yulianaboglione** [comment]
Hola
Que hizo para solucionar este error?

**Comment by ivard** [comment]
> 

We solved it by not upgrading to Go 1.20 yet. We kept using Go 1.19.

**Comment by yulianaboglione** [comment]
Y como hago para volver a la versión anterior de go? 1.19?

**Comment by ivard** [comment]
There is no universal answer on that question. It depends on your situation.
