### ISSUE TITLE
iOS camera stays active after scanning QR code

### ISSUE THREAD

**Issue by imrejonk** [privacybydesign/irmamobile#12]
### Expected behaviour
The camera should be deactivated after scanning the QR code, as well as after closing the QR view.

### Actual behaviour
The green camera indicator in the upper right-hand corner stays active, even after the QR code has been scanned. The camera also makes a sound as if it is focussing. Pressing the home button takes the app to the background, temporarily deactivating the camera, only to resume when the app is opened again. The only way to fully deactivate the camera is to close the app by double-tapping the home button and swiping up.

iPhone model: iPhone SE (2nd generation)
iOS version: 14.2
App version: 6.0.10

**Comment by ivard** [comment]
Thanks for the detailed report. We'll dive into it. We have some ideas on where it goes wrong, so I'll come back to this soon.

**Comment by ivard** [comment]
We added a fix in commit 1ae43b2c710bbc07d9923e0d0e2c6690eb262135 and, among other fixes. it is now published in the beta channel of the IRMA app. There you can test it already. When it appears to be stable, it will be pushed to all users. Thanks again for the bug report!

**Comment by imrejonk** [comment]
I'd be happy to test this. Can you share the TestFlight link?

**Comment by ivard** [comment]
Of course, you are very much welcome to do so. Below you can find the links.
- [TestFlight iOS](https://testflight.apple.com/join/rCbKypnS)
- [Android beta channel](https://play.google.com/apps/testing/org.irmacard.cardemu)

**Comment by ivard** [comment]
It concerns version `6.0.11+124`. Sometimes it takes some time before versions become visible in test flight, so it might not be there immediately.

**Comment by imrejonk** [comment]
Works perfectly, glad you could fix this!
