### ISSUE TITLE
UX suboptimal for cards with an alert

### ISSUE THREAD

**Issue by ehotting** [privacybydesign/irmamobile#13]
Cards with an issue, say 'expired', have a little alert icon instead of the three dots icon.

This alert icon does not invite interaction. If you want to delete a card due to being expired, you have to search and try to find out how you can delete it.

This can easily be fixed by adding the three dots icon for every card, and then display the alert icon just to the left of it. That way the interaction options for every card are the same, and for some cards you get an alert icon that indicates it is recommended to interact with them

**Comment by MikeClickr** [comment]
My suggestion would be:

- Display the alert icon only when the card is stored in the wallet
- Display three dots when a card has focus.

Rationale: the alert works as a trigger for the user to check it. Once opened, the focus should be on viewing contents and refresh or delete the card.

**Comment by ivard** [comment]
That will not fully work, since the three dots can also be pressed when the card hasn't focus now. Of course that can be disabled, but then there is the strange behaviour that a thee dot button is visible that cannot be pressed in some scenarios. That might also be confusing I think.
