### ISSUE TITLE
irmamobile project not runnable with flutter

### ISSUE THREAD

**Issue by MarkVeh** [privacybydesign/irmamobile#19]
I am trying to run the irmamobile project with flutter run, after following all the described steps in readme. 
The output from the flutter run looks like this:

`lib/src/screens/pin/pin_screen.dart:64:13: Error: No named parameter with the name 'child'.
            child: PinWrongAttemptsDialog(
            ^^^^^
../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/material/dialog.dart:1035:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/screens/pin/pin_screen.dart:75:13: Error: No named parameter with the name 'child'.
            child: PinWrongBlockedDialog(blocked: pinState.blockedUntil.difference(DateTime.now()).inSeconds),
            ^^^^^
../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/material/dialog.dart:1035:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/screens/change_pin/change_pin_screen.dart:136:17: Error: No named parameter with the name 'child'.
                child: PinWrongAttemptsDialog(attemptsRemaining: state.attemptsRemaining),
                ^^^^^
../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/material/dialog.dart:1035:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/screens/enrollment/widgets/introduction.dart:40:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
../../flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.0/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../../flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/delegate_widget.dart:194:18: Error: Superclass has no method named 'inheritFromEle
ment'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
../../flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:259:19: Error: The method 'inheritFromWidgetOfExactType' isn't defin
ed for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:260:19: Error: The method 'ancestorInheritedElementForWidgetOfExactT
ype' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter_windows_2.0.3-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.
        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.
`

It seems like _lib\src\screens\pin\pin_screen.dart_ uses a `child` parameter from flutters `showDialog` in _dialog.dart_, which is not supported anymore and was removed in december 2020. Similar thing could be the problem with `resizeToAvoidBottomPadding` from _lib/src/screens/enrollment/widgets/introduction.dart_ .

**Comment by sietseringers** [comment]
Thanks for reporting. We have not yet upgraded to flutter 2.x. The last version of 1.x should work, however (1.22.6).

**Comment by MarkVeh** [comment]
@sietseringers all right, thanks. maybe that would be worth mentioning in the readme.

**Comment by camfindlay** [comment]
@MarkVeh I've opened a PR to include this version reference for others hitting the same issue :D Please see if the change is helpful.

**Comment by camfindlay** [comment]
@ivard has mentioned in the linked closed PR that this should now build using flutter 2.x

**Comment by ivard** [comment]
Yes, in fact it only works when you build using flutter 2.x now because of the breaking changes :)

We tested it using Flutter 2.2.3, but don't see any reason why it wouldn't work using the latest stable Flutter release of last week (2.5.0). If you run into problems, please let us know. For now, I'll mark this story has fixed.
