### ISSUE TITLE
IRMA credentials with demo schema not working since update App

### ISSUE THREAD

**Issue by sgort** [privacybydesign/irmamobile#2]
With the recent UX update of the IRMA app my local development setup stopped working. Error message: 0 https: remote server does not use https. Before the updat IRMA app didn't require https for localhost...

![image](https://user-images.githubusercontent.com/25812095/84031836-abc19300-a996-11ea-9d2d-b5392d863ce1.png)

I use the `irma server -v --static-path examples/browser` for my convenience to work with.

**Comment by sietseringers** [comment]
This is because by default the app will now only accept https, unless a new [developer mode](https://irma.app/docs/irma-app/#developer-mode) is enabled.

**Comment by sgort** [comment]
Check. Demo working again ;-)
