### ISSUE TITLE
alpha / beta build flavors?

### ISSUE THREAD

**Issue by camfindlay** [privacybydesign/irmamobile#24]
Getting up and running with building this project for Android at present.

Can I get some further information (perhaps it can be added to the docs, happy to write them and submit a PR if I can get the information) on how the build flavors are used/named in irmamobile?

What do I get if I build for `beta` over `alpha` flavor in the resulting app?

Is `alpha` more production ready than `beta` or the other way around?

Many thanks :D

**Comment by ivard** [comment]
The names can be a bit confusing indeed. Both flavors build exactly the same app, only the app identifier differs. 

The `beta` flavor (could also have be called `production`) uses the exact same app identifier as the app in the Play Store (`org.irmacard.cardemu`). Advantage is that it exactly behaves as the Play Store IRMA-app, but the disadvantage is that it overrides the Play Store IRMA-app on your phone.

To circumvent that, we have the `alpha` flavor build that uses an alternative app identifier (`foundation.privacybydesign.irmamobile.alpha`). That one can be side-loaded besides the official IRMA-app. Disadvantage of that version is that universal app links don't work when trying to do a mobile session.
