### ISSUE TITLE
Option to disable FlutterPrivacyScreen

### ISSUE THREAD

**Issue by vanbroup** [privacybydesign/irmamobile#26]
It would be great to have an option to disable the FlutterPrivacyScreen, while the purpose of the FlutterPrivacyScreen is obvious and important, it can sometimes be useful to have the ability to take screenshots for debug purposes or to demo the APP using a screencast.

Some banking apps provide the same option in the settings.

**Comment by sietseringers** [comment]
I agree, thanks for your feedback. We'll look into it.

**Comment by ivard** [comment]
This should be available now in 'Settings' by enabling the 'Enable screenshots` setting.
