### ISSUE TITLE
Panic when an error occurs in Go

### ISSUE THREAD

**Issue by pieterbos** [privacybydesign/irmamobile#28]
On several android phones, the Irma app gives an error when scanning a QR phones. Attached are photos of the error in the app. 

The problem occurs on several Android phones that we tested. Other phones worked fine. I do not know if iOS is affected. The screenshot is of my personal Pixel 6a with android 12. Doing a full deinstall followed by a reinstall of the app does not solve the problem.

There is a bit of urgency here, apart from that such an error probably always is urgent in these kinds of apps. As you may know, Irma is being used by the Nuts Foundation, to authenticate users in sharing data in Healthcare. next week is the second hackathon for the eOverdracht-project, in which several vendors are testing their first use case on the nuts network, and will try to get their applications to share data in the nuts acceptance network. This cannot work without the Irma app functioning as intended.

What I did:
- get email plus personal data (digid) attributes in the irma app
- Scan a QR code that requests first name, last name and email attributes
- The following stack trace appears
![Photo on 29-09-2022 at 10 18](https://user-images.githubusercontent.com/21126/192979901-f3a2b6d6-8a09-47db-93c0-755b0bcc86d1.jpg)
![Photo on 29-09-2022 at 10 17 #2](https://user-images.githubusercontent.com/21126/192979909-d6f6fe19-d026-4d4b-a2b0-e9ddd79b0cc4.jpg)

**Comment by ivard** [comment]
Hi Pieter,

How unfortunate to hear. We see the stacktraces in our error reporting indeed. Does it happen structurally or does it happen sometimes? And do you use specific features in your session, like [chained sessions](https://irma.app/docs/chained-sessions/)?

The panic is caused by an issue in the error processing, so it's hard for us to determine the exact issue until we solved the error processing bug.

**Comment by stevenvegt** [comment]
What is the estimate on fixing the error processing bug?

**Comment by pieterbos** [comment]
It happens structurally on my phone, every time I try it. Same with others. We use the same setup as in the nuts documentation at https://nuts-node.readthedocs.io/en/latest/pages/getting-started/5-irma-contract.html , but with a newer irma js library (0.4.3). I will check the Nuts node code on what specific features it uses.

**Comment by pieterbos** [comment]
I think we found the issue: this was a development server, and the development mode in the Irma app was not enabled. I enabled the development mode in the Irma app and the error went away. Then this is at least a very ugly error, maybe more.

Our next step is testing with a non-development Irma server.

**Comment by ivard** [comment]
Okay, nice that you managed to find the issue. Then the only issue that's left is that the error message is not shown, but is being masked by a panic that occurs while trying to handle the error. I'll changed the title of this issue.

**Comment by ivard** [comment]
Fix in irmago is being made https://github.com/privacybydesign/irmago/pull/247
After that, we have to update the irmago dependency here to resolve the issue.

**Comment by stenreijers** [comment]
Is this fixed?
