### ISSUE TITLE
Tekst voorstel en UI opmerkingen in 'bellen' scherm

### ISSUE THREAD

**Issue by BramWithaar** [privacybydesign/irmamobile#8]
![image](https://user-images.githubusercontent.com/6553486/90245421-ecc0a280-de32-11ea-817b-60937dfe507d.png)

In dit scherm de tekst aanpassen naar:
"Wil je de volgende persoonlijke gegevens delen met gemeente Nijmegen en bellen naar xxxxx? "

•	'Dit' in de huidige tekst is niet duidelijk, dus concretiseren
•	Dikdrukken van organisatie en telefoonnummer zou ik hanteren.
•	Tekst knoppen: 'Nee, liever niet' is gek. Je kunt namelijk niet bellen als je je gegevens niet bekend maakt. Dus gewoon 'Nee'. 
•	Ik vind persoonlijk de interface niet helemaal duidelijk. Door de de vraag bovenin de plaatsen en de knoppen onderin moet ik even nadenken en goed kijken wat ik moet doen. Nadat dit scherm opent valt mijn oog namelijk gelijk op de knoppen (waarschijnlijk door het kleurgebruik maar ook door het grote witte vlak daarboven/ onder de vraag) maar snap ik niet waar deze knoppen voor dienen. Ik moest echt even zoeken naar de vraag. Kan daar iets aangedaan word qua vormgeving?

Daar zit de gotcha bij dat 'gemeente Nijmegen' natuurlijk niet de hostname is van de server waarop IRMA draait.
Voor een gebruiker is een logische naam wel veel voor de hand liggender dan een technische naam.

**Comment by ivard** [comment]
Sorry ook hier voor de late reactie, punt 3 en het laatste punt met 'gemeente Nijmegen' zit inmiddels in de pijplijn. 

Voor puntje 1, verwijswoorden zijn altijd moeilijk voor mensen. Ik kan hooguit iets bedenken nu snel als 'onderstaande', maar dat woord is dan weer niet B1. Blijft lastig.

Voor puntje 2, ze zijn nu dik gedrukt toch? Of begrijp ik je dan verkeerd?

Puntje 4 kan ik mij op grote telefoons iets bij voorstellen. Op kleinere telefoons is dit al minder een probleem. Ik kan me zo snel alleen ook niets beters bedenken. De tekst naar beneden halen, lijkt me ook onlogisch en de knoppen naar boven halen lijkt me helemaal geen optie. Had je iets in gedachte toevallig?
