### ISSUE TITLE
UI en tekst opmerkingen in 2e bellen scherm

### ISSUE THREAD

**Issue by BramWithaar** [privacybydesign/irmamobile#9]
Gaat om dit scherm:
![image](https://user-images.githubusercontent.com/6553486/90245699-76707000-de33-11ea-87c0-b7309323015e.png)

Tekstvoorstel:
In blauwe kader: i + Je persoonlijke gegevens zijn doorgegeven aan gemeente Nijmegen 

Je kunt nu bellen
Klik op doorgaan. Het telefoonnummer verschijnt dan automatisch. Achter het nummer staat een persoonlijke code. Hier hoef je niks mee te doen. 

Kies je voor bellen, dan hoor je enkele tonen. Daarna word je verbonden

Overweging hierbij:
•	Blauwe kader: er staat twee keer dat de gegevens zijn doorgegeven. 1 zin is voldoende. Sowieso is doorgegegeven geen woord.  (er staat dus sowieso een vette type in het huidige scherm)

**Comment by ivard** [comment]
Sorry dat hier zo lang niet op gereageerd is. Ik weet niet precies wat de afwegingen geweest zijn bij deze tekst. Wellicht dat @CreativeCode dat weet...

**Comment by ivard** [comment]
Het puntje dat er 'gemeente Nijmegen' zou moeten staan ipv een URL in het bericht in de blauwe box zit in ieder geval wel in de pijplijn nu. Voor de issuers werkt dat al en verifiers komen daar tzt ook bij.
